### PR TITLE
feat: switch from follow to cloudant-follow, which is maintaned

### PR DESCRIPTION
**Pull request by janl**

### CODE REVIEW

**Comment by janl** [comment]
ping @garrensmith @glynnbird @jo

**Comment by jo** [comment]
+1

**Comment by ricellis** [comment]
I think the next best option is to take the follow code into this library and maintain it here. It is one file and Apache 2 licensed.

**Comment by glynnbird** [comment]
If we want to bring the `follow` code into this project, then I'm happy to volunteer to write a PR to do that? What do you think @janl ?

**Comment by loay** [comment]
looks good to me. That will fix the security issue of `request` and `hawk`. Please merge.

**Pull request merged**
