### PR TITLE
bring follow library under Nano's wing

### PR DESCRIPTION
**Pull request by glynnbird**
## Overview

Currently Nano uses a the [follow](https://www.npmjs.com/package/follow) library as a dependency to handle changes feed subscription. Unfortunately, `follow` is not maintained. The nice people at Cloudant have taken the code and fixed it up and published it [here](https://github.com/cloudant-labs/cloudant-follow).  This [PR](https://github.com/apache/couchdb-nano/pull/51) proposes to depend on the  cloudant-follow fork, but I am proposing something different:

1) Bring the follow codebase into the Nano project (it is published under an Apache-2.0 license)
2) Remove follow as a dependency
3) In the future refactor the follow code to be more in keeping with this project 

## Testing recommendations

This should be a drop-in replacement of the previous version. The only difference is that the `follow` code lives in this repo and not as a dependency.

I've brought in the `follow` tests too. Unfortunately they rely on CouchDB1.6 so I've altered the testing sequence to run our core tests with CouchDB2 then switch over to CouchDB1.6 for the follow tests.

See `npm run coretests` & `npm run followtests` in package.json.

## Related Pull Requests

See issue #28 & pull #51 

## Checklist

- [x] Code is written and works correctly;
- [x] Changes are covered by tests;
- [x] Documentation reflects the changes;

### CODE REVIEW

**Comment by SinanGabel** [comment]
Really good plan!

**Comment by wohali** [comment]
@glynnbird FYI, any new code to be brought under an ASF repository (and thus ownership) directly must go through the code clearance process as outlined here:

    https://incubator.apache.org/guides/ip_clearance.html

It's not just a matter of "they licensed it AL v2.0 so we can just bring it into our repo." That may be true of dependencies (we can depend on compatibly licensed code with no extra paperwork) but it's not true when that code is going to live in our repositories.

Now, that said, if Cloudant people have "maintained out" most of the original developers' changes, i.e. "git blame" doesn't show their contributions as still being in place, then we can waive that process under the outstanding Cloudant CCLA + jhs's outstanding ICLA. You'll need to do the legwork here to ensure that is the case.

- Joan with her "PMC hat" on.

**Comment by glynnbird** [comment]
Thanks for the clarification @wohali I'll make some enquiries.

**Comment by janl** [comment]
@glynnbird see https://github.com/dscape/nano/issues/265 for how we did it for nano

**Comment by jhs** [comment]
Hi, Joan and Glynn. I authored Follow and I am already a CouchDB committer.
Does that help smooth the process?

**Comment by wohali** [comment]
@jhs It helps a lot - but we should follow the ASF guidelines here.

@janl 's recommendation to review dscape/nano#265 to see how we did it for nano is wise. Collect a full list of all contributors and get them to sign CLAs. Anyone whose changes are "eclipsed" (`git blame` is your friend here) doesn't need to sign a CLA. If we can't contact some of the individuals involved, we can do a further review process to determine if it's a problem or not.

**Comment by glynnbird** [comment]
Thanks

**Pull request closed without merging**
