### PR TITLE
Add detailed error message (fixes issue #58)

### LINKED ISSUE #58: Provide more information for socket errors
It would be helpful to provide additional error information in the message Nano outputs for socket or connection errors.

## Expected Behavior

Suggest including, for example, reading the error `.code` and `.description` and adding it to the message to provide some more useful diagnostics.
```js
{
  code: 'ECONNRESET',
  description: 'socket hang up'
}
```
err.message -> `error happened in your connection ECONNRESET socket hang up`

## Current Behavior

Currently for a socket/connection error only the `err.message` is set to `error happened in your connection`.

err.message -> `error happened in your connection`

## Possible Solution

Could build up the error message to include `.code` and `.description` if they are available e.g.
```
  if (err && err.code) {
    err.message = `${err.message} ${err.code}`;
  }
  if (err && err.description) {
    err.message = `${err.message} ${err.description}`;
  }
```

## Steps to Reproduce (for bugs)

1. Could use nock `replyWithError` to reproduce e.g.
```js
nock.get(...).replyWithError({'description': 'socket hang up', 'code': 'ECONNRESET'});
```

## Context

Made it hard to debug some connection issues without adding additional output statements to see the underlying cause of the error. Similarly to #54 where the whole error object has been output because the message `error happened in your connection` is insufficient to identify the issue.

## Your Environment

* Version used:
>6.4.0
* Browser Name and version:
>Node.js 8.2.0
* Operating System and version (desktop or mobile):
> macOS 10.12.6
* Link to your project:
>https://github.com/cloudant/nodejs-cloudant

### PR DESCRIPTION
**Pull request by gboer**
## Overview

When encountering issues with connecting to CouchDB, the only error you get is "error happened in your connection". This is extremely unhelpful in debugging the issues. So instead, I've added the actual reason things are failing, so that it's easier for people to figure out what's wrong.

## Testing recommendations

There's a unit test that already covered it.

## GitHub issue number

Fixes #58 

## Checklist

- [ x ] Code is written and works correctly;
- [ x ] Changes are covered by tests;
- [ x ] Documentation reflects the changes;

### CODE REVIEW

**Comment by gboer** [comment]
I also updated the CONTRIBUTING.md, since the mocked/unmocked scripts don't seem to exist anymore. I guess they were replaced with Jest at some point?

**Comment by gboer** [comment]
@glynnbird do you have some time to look at this PR? It would really help debugging people's connections issues.

**Review by glynnbird — APPROVED** [review]
LGTM

**Comment by gboer** [comment]
Awesome, thanks!

**Comment by gboer** [comment]
@glynnbird did something go wrong with releasing this fix? Can I assist in some way to get this released on npm?

**Comment by glynnbird** [comment]
@gboer it'll get released this week.

**Comment by gboer** [comment]
ah, great! Thanks for the reply @glynnbird  :)

**Pull request merged**
