### PR TITLE
add reference to server in doc scope

### PR DESCRIPTION
**Pull request by dominicbarnes**
This PR is ported from dscape/nano#346

### CODE REVIEW

**Comment by garrensmith** [comment]
Thank you, could you rebase this against master I've pushed a lot of fixes that @glynnbird has been working on.

**Comment by dominicbarnes** [comment]
Rebase complete!

**Comment by glynnbird** [comment]
+1 from me

**Comment by garrensmith** [comment]
Thanks. I've merged it in.

**Comment by garrensmith** [comment]
@dominicbarnes could you close this PR now.

**Comment by dominicbarnes** [comment]
How long until this change (and the other improvements being made) get released to npm?

**Pull request merged**
