### PR TITLE
Fix nano.d.ts: Add FollowEmitter.stop() to typescript declaration file

### PR DESCRIPTION
**Pull request by sxwei123**
## Overview

The feed of `cloudant-follow` can be stopped by calling `stop()` method. It is missing from the `nano.d.ts` file.
https://www.npmjs.com/package/cloudant-follow#events

## Testing recommendations

Changes to typescript definitions only, no code modified.

## GitHub issue number

NA.
## Related Pull Requests

NA.
## Checklist

- [x] Code is written and works correctly;
- [x] Changes are covered by tests;
- [x] Documentation reflects the changes;

### CODE REVIEW

**Review by insidewhy — APPROVED** [review]

**Comment by insidewhy** [comment]
@YC This is a very simple fix, can you merge this? It looks like not many commits are happening to this repo anymore, is it possible to add more maintainers?

**Comment by glynnbird** [comment]
Thanks for the feedback. This project is updated on a voluntary basis by unpaid volunteers. If you'd like to volunteer your time to the project, then I'm sure the extra pair of hands would be welcome.

**Review by glynnbird — COMMENTED** [review]
LGTM

**Comment by insidewhy** [comment]
@glynnbird sure. BTW https://github.com/apache/couchdb-nano/pull/231 is another simple PR and quick win.

**Pull request merged**
