### PR TITLE
[DISCUSSION] For your consideration: move linting to standard

### PR DESCRIPTION
**Pull request by janl**
See https://github.com/apache/couchdb-nano/issues/104 for details and reasoning

### CODE REVIEW

**Comment by garrensmith** [comment]
Moving away from jshint is a great idea. I'm not a huge fan of standard because of its lack of semi-colons but that is a personal opinion so I won't stop this PR based on that.

**Comment by janl** [comment]
@garrensmith the thing I care about most is not having to maintain a linter config. In the projects I‘ve been involved in the past three years, I let other make the call on how to lint and every single one of them eventually went to standard, and today I can say it is so freeing to have a zero config linter. It’s worth to me way more than any idiosyncrasies (It allows `if (foo) bar` without the optional curlies, blasphemy! And don’t get me started on not being able to start a block with an empty line) that I might run up against. I got over semicolons eventually, too.

The PR title says `DISCUSSION` though for a reason. I wanted to show that a transition to a new linter is possible and not that hard. I don’t wanna just create facts and pull the community along in a way it doesn’t wanna go.

Ping @jo @glynnbird

**Comment by jo** [comment]
+1

**Comment by garrensmith** [comment]
No linter config is nice and something that is familiar to devs across projects is also a huge help. I'm +1 if @glynnbird is happy since he has done all the work for the latest updates.

**Comment by glynnbird** [comment]
@janl Travis is complaining because `package-lock.json` & `package.json` are not in sync. You could try deleting `package-lock.json` and doing a fresh `npm install`.

**Comment by janl** [comment]
@glynnbird thanks, I’ll sort out those build issues. In the meantime, what do you think about the proposal?

**Comment by glynnbird** [comment]
I approve of this idea. When I came to approve it, I notice that changes to master had made the merge of this code almost impossible. Out of guilt for having merged other changes first, I recreated the thrust of this PR here: https://github.com/apache/couchdb-nano/pull/116

**Pull request closed without merging**
